# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'ZHWTipText' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZHWTipText

    pod 'Masonry', '~> 0.6.3'

  target 'ZHWTipTextTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZHWTipTextUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
